### ISSUE TITLE
Add free-text configuration for warmup iterations instead of dropdown

### ISSUE THREAD

**Issue by jsoules** [flatironinstitute/mcmc-monitor#2]
Per @wardbrian's request.

**Comment by magland** [comment]
For this I think we should try to strike a balance between a dropdown menu and entering custom amount. The former is a lot more user-friendly in cases where it is suitable.

(as Brian pointed out to me the other day) In the Stan output there is a comment line `# Adaptation terminated` that is inserted at the end of the warmup draws. We could pass this information (numWarmupDraws) to the front-end, and this could become one of the options in the dropdown (marked with an asterisk or something).

We could also have one of the dropdown options be "Custom" and at that point a text box would appear.

We should also consider having this default to `None`, rather than the arbitrary "20".

**Comment by WardBrian** [comment]
If you had the logic to detect `# Adaptation terminated`, I suspect the only selections people would use are either that one or 0. Having the rest of the existing options or a more customizable one would be nice if these CSVs aren't from Stan specifically

**Comment by magland** [comment]
@jsoules 

Here's where we'll want to detect the `# Adaptation terminated` line and store the number of draws/iterations to that point:

https://github.com/flatironinstitute/mcmc-monitor/blob/459e8b6814c745bbf7681f3035b409177a540057/service/src/ChainFile.ts#L153-L167

Note that this will be tracked separately for each chain. Even though number of warmup draws is going to be equal across all the chains, I think it's okay to track this separately, and keep this a property of the chain. Then on the front-end, we'll just look at the first chain to get the info.

Here is where we'll want to return the numWarmupDraws info (if defined):

https://github.com/flatironinstitute/mcmc-monitor/blob/459e8b6814c745bbf7681f3035b409177a540057/service/src/OutputManager.ts#L62-L69

And of course we'll need to add that field to the MCMCChain type.

**Comment by jsoules** [comment]
So there was a bit of a discrepancy in the definition of this issue. I take @WardBrian to be requesting that we offer a value in the dropdown that says "Read the number of warmup adaptations from the file," whereas @magland is suggesting that we read the number from the file (if it exists) and then add that number to the dropdown with some indicator that it's from the file (for example by adding an asterisk).

I can see the appeal of both, but my initial understanding of the request was what I think Brian is asking for, so that's what I wound up implementing in my pr #12. If we want the other functionality, that shouldn't be too hard to arrange.

**Comment by WardBrian** [comment]
My original request was less imaginative and was just for a text box I could put any number in. After discussion here, I think that @magland’s suggestion is the best.

To my mind, if that number exists, it is the obvious default choice in the drop down. If it doesn’t (either because warmup is still ongoing or because it is 0) then 0 is probably the best default in that case

**Comment by jsoules** [comment]
So here's the current version of the functionality proposed in pr #12:
https://flatironinstitute.github.io/mcmc-monitor/dev/index.html?s=https://lit-bayou-76056.herokuapp.com#/run/multi-normal-2

Does this fulfill the feature request? Any further tweaks to recommend in terms of the delivered functionality?

**Comment by WardBrian** [comment]
That looks like the functionality I'd like, yes!

For clarity "Read from file" may not be the best name, maybe "Warmup draws from file (20)" (if that isn't too long!)

**Comment by magland** [comment]
Looks great!
When using systems other than Stan, "Read from file" or "Warmup draws from file" may not be exactly correct. What do you guys think about "Auto detect (20)"?

**Comment by jsoules** [comment]
Changed text, redeployed to dev.
