### ISSUE TITLE
Provide an informative error when the service is out of date

### ISSUE THREAD

**Issue by WardBrian** [flatironinstitute/mcmc-monitor#25]
Right now, if you manually install version `0.1.10` (while the latest is `0.1.11`), the web UI displays a generic error which doesn't mention a version issue:
![image](https://user-images.githubusercontent.com/31640292/223240988-184873ed-9fd0-4d73-917c-94686651f34b.png)

The browser console, on the other hand, does say 
```
16:40:51.546 Error: Unexpected protocol version: 0.1.3 <> 0.1.4
    qO https://flatironinstitute.github.io/mcmc-monitor/assets/index-2f6c0d9a.js:167
```

**Comment by jsoules** [comment]
So this is sort-of WAI, but probably not the greatest UX.

On the client side, it is true that you aren't connected to the service, and the JS console does say why. But we should probably put that information into the page itself, since most users aren't going to know to check the browser console.

On the server side, the server is not doing a check with the client's protocol version (which I don't believe even gets sent). The server will just try to talk back to whatever requests it gets. There's a bit of a question about a) whether anybody will be monitoring the server's output and b) what the server would do with this information if it did appear--I expect the right thing would be to encourage the user to upgrade if the server starts getting messages from clients-from-the-future.

So I'm going to mark the fix for this issue as "Protocol version mismatches on client side are displayed in the page directly instead of only in the console."

And I'll open up a separate ticket for the server to get, and do something with, information about the protocol versions of requests it is receiving.

**Comment by WardBrian** [comment]
I don’t think it’s important to show anything in the service output, I just included the terminal in my screenshot to show that the service actually was running at that address/port
