### ISSUE TITLE
Document developer instructions

### ISSUE THREAD

**Issue by magland** [flatironinstitute/mcmc-monitor#3]
We'll want to provide instructions for developers. I think we should recommend using vscode. Roughly:

* clone the repo
* `yarn install` then `yarn dev`
* `cd service`, `yarn install`, `yarn dev` (optional - only needed if developing the service rather than the GUI)
* Generate sample data (or use example data hosted on heroku)

Open locally. Note that this is using vite rather than CRA. I found it to be much faster and leaner.

Instructions for deploying...
Fork the repo... and deploy to gh-pages of the forked repo. However, we probably don't want people to be using other competing versions of this software (it's so easy to deploy one's own). So we'll want to put something in the readme explaining that people should contribute to the main repo via PRs. We do want to encourage forking for purpose of contributing features, but not for purpose of forking the project (please).

**Comment by jsoules** [comment]
Note, may also need to `yarn install ts-node` in the `service` directory for `yarn dev` to work there.

**Comment by magland** [comment]
> Note, may also need to `yarn install ts-node` in the `service` directory for `yarn dev` to work there.

Thx. I added ts-node to package.json (`yarn add -D ts-node`) and pushed directly to main.

**Comment by jsoules** [comment]
Note for writeup:

- Developing on the service (`mcmc-monitor/service/` and child directories) and developing on the client and gui (i.e. everything else) are separate and require running separate local services.

- When developing on the gui/client, you'll need to run the `vite` server for the front-end and client code, by executing `yarn dev` in the main `mcmc-monitor` directory. The resulting service will give a `localhost` address (e.g. `http://localhost:5173/mcmc-monitor`) which should be used for testing changes to the client.

- When developing on the server (changes made in `mcmc-monitor/service/` directory and children) that's when you'll need to use `yarn dev` in the `service` directory.

- If you are developing on both server and client, to test your changes you'll need to run both local servers.

- The service is not aware of whether the gui/client are also being edited--it will still output URLs that reference the github-deployed (published) version of the client code. If you are changing both parts of the application, you will need to edit the URL output by the MCMC-Monitor service (e.g. `https://flatironinstitute.github.io/mcmc-monitor?s=http://localhost:61542`) so that it points to the local client (e.g. `http://localhost:5173/mcmc-monitor?s=http://localhost:61542`).
  - Note the change from `flatironinstitute.github.io` to `localhost:5173` and that the local server uses `http` not `https`. (Port 5173 is a default for the `vite` server, but be sure to check your local instance output as the actual port may vary based on your system configuration.)
