### ISSUE TITLE
does this run in Safari?

### ISSUE THREAD

**Issue by mitzimorris** [flatironinstitute/mcmc-monitor#98]
on my machine, this doesn't work on Safari but it does in Chrome.    perhaps it's a Safari config issue?

**Comment by jsoules** [comment]
Could you provide a bit more information about the configuration? Are you getting any kind of error message?

I can confirm that the example site, at least, does work in Safari on an iPhone (in landscape mode specifically--the default width for the left-hand control panel is too wide to see the content pane in portrait orientation) but I haven't tried it on a Mac proper.

@magland have you tried it with non-mobile Safari?

**Comment by mitzimorris** [comment]
running the monitor, can see it on Chrome, but then copying the URL into Safari gives this:

<img width="1012" alt="safari" src="https://github.com/flatironinstitute/mcmc-monitor/assets/5466612/af919258-a2fe-4e98-9682-58ba0534e7e4">

Safari is 16.4.1. 
my OS is 12.6.5 ("Monterey")
although I have ad blockers, the message suggests the problem is elsewhere and turning off the ad blockers didn't do anything.   my settings are vanilla, other than preventing cross-site trackers.

**Comment by magland** [comment]
On Wednesday I will have access to a macbook, so I'll try it out there. (It seems that this is an issue where the browser is not allowing the website to connect to a local service.)

**Comment by magland** [comment]
@mitzimorris and @jsoules 

I confirm that monitoring of a local service does NOT work in safari on a mac. This I believe is due to a safari security policy of not allowing an https site from accessing content from a http endpoint (not 100% sure about this, but it's what I have gathered). There's no good workaround for this as far as I know. However, this ONLY affects monitoring of a local service... you can still use MCMC Monitor on safari if you are monitoring a remote service, or if using the proxy.

I think we should update the docs to say to use chrome or firefox and note that safari also works except in the case of monitoring a local service directly.
